name: CI
on: 
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

jobs:
  "Build-Examples":
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        example: 
        - EventSources
        - SquareNumber
        - TodoAPIGateway
        - URLRequestWithSession
    env:
      SWIFT_VERSION: 5.2.1
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install ruby
      uses: actions/setup-ruby@v1
    - name: Build Docker Swift Dev Image
      run: docker build --build-arg SWIFT_VERSION=${SWIFT_VERSION} -t fabianfett/amazonlinux-swift:${SWIFT_VERSION}-amazonlinux2-dev ./docker
    - name: Build example
      run: |
        cd examples/${{ matrix.example }}
        make package_lambda
    - name: Install sam cli
      if: matrix.example == 'SquareNumber'
      run: sudo pip install aws-sam-cli
    - name: Download layer
      if: matrix.example == 'SquareNumber'
      run: |
        cd examples/${{ matrix.example }}
        make download_layer
    - name: Run example
      if: matrix.example == 'SquareNumber'
      run: |
        cd examples/${{ matrix.example }}
        echo '{"number": 9 }' | sam local invoke -v . "SquareNumberFunction"
        echo '{"number": 3 }' | sam local invoke -v . "PrintNumberFunction"
        
  "tuxOS-Tests":
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images:
        - swift:5.1.5
        - swift:5.2.1
    container:
      image: ${{ matrix.images }}
      volumes:
      - /workspace:/src
      options: --workdir /src
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install dependencies
      run: apt-get update && apt-get install -y zlib1g-dev zip openssl libssl-dev
    - name: Test
      run: swift test --enable-code-coverage --enable-test-discovery
    - name: Convert coverage files
      run: llvm-cov export -format="lcov" .build/debug/swift-lambda-runtimePackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}}

  "macOS-Tests":
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Show all Xcode versions
      run: ls -an /Applications/ | grep Xcode*
    - name: Change Xcode command line tools
      run: sudo xcode-select -s /Applications/Xcode_11.4.app/Contents/Developer
    - name: SPM Build
      run: swift build
    - name: SPM Tests
      run: swift test --parallel -Xswiftc -DDEBUG
    - name: Xcode Tests
      run: |
        swift package generate-xcodeproj
        xcodebuild -quiet -parallel-testing-enabled YES -scheme swift-lambda-runtime-Package -enableCodeCoverage YES build test
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash) -J 'LambdaRuntime' -t ${{secrets.CODECOV_TOKEN}}
